export const images: { src: string; alt: string; caption: string; type: 'image'; }[] = [
  {
    src: "/074979f7-d726-4c43-ba46-83bc21bee1c5.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/333d2fd4-1ad8-4755-9f27-5868a97deba8.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/47d480d3-a154-4a18-bdcc-7638c789f64e.JPG",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG-20230621-WA0000.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG-20230621-WA0003.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG-20230621-WA0004.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG-20230623-WA0026.jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG-20230623-WA0027.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG-20230623-WA0028.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG-20230623-WA0029.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG-20230623-WA0030.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG-20230624-WA0035.jpg",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG-20230624-WA0036.jpg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG-20230702-WA0022.jpg",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/IMG-20230702-WA0023.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/IMG-20230702-WA0024.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/IMG-20230702-WA0025.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG-20230702-WA0026.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0027.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0079.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0080.jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0081.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0082.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0083.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0084.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0085.jpg",
    alt: "A beautiful image",
    caption: "You are the love of my life",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0086.jpg",
    alt: "A beautiful image",
    caption: "I will always love you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0087.jpg",
    alt: "A beautiful image",
    caption: "You are my forever",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0088.jpg",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0089.jpg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0090.jpg",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0092.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0094.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0095.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0096.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0097.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0098.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0100.jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0101.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0102.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0103.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0104.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0105.jpg",
    alt: "A beautiful image",
    caption: "You are the love of my life",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0106.jpg",
    alt: "A beautiful image",
    caption: "I will always love you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0108.jpg",
    alt: "A beautiful image",
    caption: "You are my forever",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0109.jpg",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0110.jpg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0111.jpg",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/IMG-20230705-WA0112.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/IMG-20230706-WA0008.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/IMG-20230706-WA0010.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG-20230706-WA0011.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG-20230706-WA0012.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG-20230706-WA0013.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG-20231013-WA0011.jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG-20231126-WA0000.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG-20231129-WA0002.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG-20231219-WA0020.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG-20231222-WA0019.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG-20240107-WA0002.jpg",
    alt: "A beautiful image",
    caption: "You are the love of my life",
    type: "image",
  },
{
    src: "/IMG-20240107-WA0052.jpg",
    alt: "A beautiful image",
    caption: "I will always love you",
    type: "image",
  },
{
    src: "/IMG-20240107-WA0056.jpg",
    alt: "A beautiful image",
    caption: "You are my forever",
    type: "image",
  },
{
    src: "/IMG-20240107-WA0072.jpg",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG-20240107-WA0073.jpg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG-20240109-WA0006.jpg",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/IMG-20240205-WA0026.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/IMG-20260121-WA0036.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/IMG-20260121-WA0039.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG-20260121-WA0040.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG-20260121-WA0041.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG-20260121-WA0042.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG-20260203-WA0023(1).jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG-20260203-WA0023.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG-20260203-WA0024.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG-20260203-WA0025.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG-20260203-WA0026.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG_0913.HEIC",
    alt: "A beautiful image",
    caption: "You are the love of my life",
    type: "image",
  },
{
    src: "/IMG_1052.HEIC",
    alt: "A beautiful image",
    caption: "I will always love you",
    type: "image",
  },
{
    src: "/IMG_1053.HEIC",
    alt: "A beautiful image",
    caption: "You are my forever",
    type: "image",
  },
{
    src: "/IMG_1054.HEIC",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG_1065.JPG",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG_20231003_131108_721.jpg",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/IMG_20231004_122330_689.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/IMG_20231114_150016_798.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/IMG_20231129_121708_229.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/IMG_20231129_131207_095.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/IMG_20240117_113233_351.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/IMG_20240125_160924_692.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/IMG_2263.JPG",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/IMG_2503.HEIC",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/IMG_2504.HEIC",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/IMG_2620.JPG",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/IMG_2626.JPG",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/IMG_2634.JPG",
    alt: "A beautiful image",
    caption: "You are the love of my life",
    type: "image",
  },
{
    src: "/IMG_4779.JPG",
    alt: "A beautiful image",
    caption: "I will always love you",
    type: "image",
  },
{
    src: "/IMG_7959.JPG",
    alt: "A beautiful image",
    caption: "You are my forever",
    type: "image",
  },
{
    src: "/IMG_7960.JPG",
    alt: "A beautiful image",
    caption: "You are my always",
    type: "image",
  },
{
    src: "/IMG_7968.HEIC",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/IMG_9714.JPG",
    alt: "A beautiful image",
    caption: "You are my one and only",
    type: "image",
  },
{
    src: "/PXL_20260127_122511800.jpg",
    alt: "A beautiful image",
    caption: "You are my everything",
    type: "image",
  },
{
    src: "/PXL_20260127_122514554.jpg",
    alt: "A beautiful image",
    caption: "You are my sunshine",
    type: "image",
  },
{
    src: "/PXL_20260127_123015959.jpg",
    alt: "A beautiful image",
    caption: "I love you to the moon and back",
    type: "image",
  },
{
    src: "/PXL_20260127_123017164.jpg",
    alt: "A beautiful image",
    caption: "You are the best thing that ever happened to me",
    type: "image",
  },
{
    src: "/PXL_20260127_123020812.jpg",
    alt: "A beautiful image",
    caption: "I can't imagine my life without you",
    type: "image",
  },
{
    src: "/PXL_20260127_123026836.jpg",
    alt: "A beautiful image",
    caption: "You make me a better person",
    type: "image",
  },
{
    src: "/PXL_20260127_123030757.jpg",
    alt: "A beautiful image",
    caption: "I love you more than words can say",
    type: "image",
  },
{
    src: "/PXL_20260127_123122060.jpg",
    alt: "A beautiful image",
    caption: "You are my soulmate",
    type: "image",
  },
{
    src: "/PXL_20260127_123123454.jpg",
    alt: "A beautiful image",
    caption: "I am so lucky to have you in my life",
    type: "image",
  },
{
    src: "/PXL_20260127_123220555.jpg",
    alt: "A beautiful image",
    caption: "You are my missing piece",
    type: "image",
  },
{
    src: "/PXL_20260127_130133939.jpg",
    alt: "A beautiful image",
    caption: "You are my happily ever after",
    type: "image",
  },
{
    src: "/Screenshot_20240105-092246.png",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ael.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/al.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/amAEW.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ap.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/awn.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/b06fa58b-2d53-469e-bb50-0d70ad493242.jpg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/babe.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/baby.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/bea.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/cute.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/des.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/dksa.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/e857564e-7b00-4e4b-a338-c5aaaa821f61.JPG",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/eas.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/hmmm.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ja.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/jg.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ka.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/kd.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/kkl.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ko.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/leals.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ll.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/london.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ls.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/mk.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ms.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/mw.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ns.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/nw.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/okaaaaaa.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ol.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/ow.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p.as.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p1.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p10.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p12.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p13.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p14.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p2.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p3.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/p4.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  },
{
    src: "/zzas.jpeg",
    alt: "A beautiful image",
    caption: "I love you",
    type: "image",
  }
];
